##    00000    000000000      00000000  000000000  0000      0000    00000    00      00  000000000  00000000
##  00     00  00     00      00    00  00         00  00  00  00  00     00  00      00  00         00    00
##  00     00  000000000      00000000  00000      00    00    00  00     00    00  00    00000      00000000
##  00     00  00             000000    00         00          00  00     00    00  00    00         000000
##    00000    00             00  0000  000000000  00          00    00000        00      000000000  00  0000

#List of players with operator status which the plugin is gonna remove the operator status after leaving.
#Add your names in this list
#Example: - OmegaByte
OpPlayerList:
  - PlayerName

LogToConsole: true
ConsoleLog: '&b&nServer&8: &aOperator status has been removed from %p after leaving the server.'
ReloadMsg: '&8[&cOpRemover&8] &aConfiguration reloaded!'
NoPermission: '&cYou do not have permissions to execute this command.'
CommandUse: '&cUse: /opremover reload'

#Don't touch this!
configVersion: 1
