name: OpRemover
version: 1.3
main: me.omega01.opremover.Main
author: Omega01
description: Removes operator status from operator's after leaving the server. (For Security)

commands:
  opremover:
    description: Main command.
    usage: /<command>
  oprecovery:
    description: Password to recover op status.
    usage: /<command>