name: OpRemover
version: 1.2
main: me.OmegaByte.OpRemover.Main
author: OmegaByte
description: Removes operator status from operator's after leaving the server. (For Security)

commands:
  opremover:
    description: Main command.
    usage: /<command>
